name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "jianjiangant@gmail.com"
          password: "jiangjian32!"

      - name: Build and push Docker image using Makefile
        run: make -C docker release_build CUDA_ARCHS="89-real;90-real"
